export const headerData = {
  en: {
    home: "Home",
    LifeAlliance: "Life @ Alliance",
    about: "About Us",
    services: "Services",
    location: "Location",
    abuDhabi: "Abu Dhabi",
    jeddah: "Jeddah",
    riyadh: "Riyadh",
    qatar: "Qatar",
    kuwait: "Kuwait",
    sharjah: "Sharjah",
    dubai: "Dubai",
    oman: "Oman",
    bahrain: "Bahrain",
    ManpowerRecruitment: "Manpower Recruitment",
    RecruitmentServices: "Recruitment Services",
    RecruitmentConsultant: "Recruitment Consultant",
    RecruitmentAgency: "Recruitment Agency",
    EmploymentAgency: "Employment Agency",
    ManpowerCompany: "Manpower Company",
    RPOServices: "RPO Services",
    HRConsultant: "HR Consultant",
    PlacementAgency: "Placement Agency",
    StaffingServices: "Staffing Services",
    TempStaffingAgency: "Temp Staffing Agency",
    ITStaffingCompany: "IT Staffing Company",
    Franchise: "Franchise",
    Executivesearch: "Executive search",
    MedicalHealthcarestaffing: "Medical-Healthcare staffing",
    Employmentagencyfranchise: "Employment agency franchise",
    HRconsultancy: "HR consultancy",
    Recruitmentagency: "Recruitment agency",
    Manpowerconsultancy: "Manpower consultancy",
    Staffingagencyfranchise: "Staffing agency franchise",
    HireCLevel: "Hire C- Level",
    CSuite: "C- Suite",
    CLevel: "C-Level",
    learnMoreAboutCLevelRecruitment: "Learn more about C-Level Recruitment",
    cxoStaffingSolutions: "CXO Staffing Solutions",
    learnMoreAboutCEORecruitment: "Learn more about CEO Recruitment",
    exploreCTORecruitmentServices: "Explore CTO Recruitment Services",
    cfoExecutiveSearchServices: "CFO Executive Search Services",
    exploreExecutiveRecruitmentDubai:
      "Explore Executive Recruitment services in Dubai",
    learnAboutCEORecruitmentServices: "Learn about CEO Recruitment services",
    discoverExecutiveChefEmployment:
      "Discover Executive Chef Employment opportunities",
    findOutExecutiveSearchDubai:
      "Find out about Executive Search services in Dubai",
    exploreCFOHeadhunters: "Explore CFO Headhunters for your recruitment needs",
    CEO: "CEO",
    CTO: "CTO",
    CXO: "CXO",
    CFO: "CFO",
    ExecutiveSearch: "Executive Search",
    ExecutiveRecruitmentDubai: "Executive Recruitment Dubai",
    CEORecruitment: "CEO Recruitment",
    ExecutiveChefEmployment: "Executive Chef Employment",
    ExecutiveSearchDubai: "Executive Search Dubai",
    Headhunter: "Headhunter",
    HEADHUNTER: "HEADHUNTER",
    ExecutiveHeadhunter: "Executive Headhunter",
    CFOHeadhunters: "CFO Headhunters",
    CTOHeadhunters: "CTO Headhunters",
    Industries: "Industries",
    WERECRUIT: "WERECRUIT FOR FOLLOWING INDUSTRIES",
    healthcare: "Healthcare",
    doctor: "Doctor",
    dentist: "Dentist",
    medical: "Medical",
    nursing: "Nursing",
    executiveChef: "Executive Chef",
    sousChef: "Sous Chef",
    shipCrew: "Ship Crew",
    cruiseShip: "Cruise Ship",
    driver: "Driver",
    teacher: "Teacher",
    it: "IT",
    legal: "Legal",
    banking: "Banking",
    accountant: "Accountant",
    construction: "Construction",
    engineering: "Engineering",
    hr: "HR",
    marketing: "Marketing",
    hospitality: "Hospitality",
    hotel: "Hotel",
    maid: "Maid",
    photography: "Photography",
    oilAndGas: "Oil and Gas",
    retail: "Retail",
    finance: "Finance",
    blog: "Blog",
    contact: "Contact Us",
    postYourVacancy: "Post Your Vacancy",
    franchiseInquiry: "Franchise Apply",
    hireATalent: "Hire a Talent",
    jobSeekers: "Job Seekers",
  },
  ar: {
    home: "الرئيسية",
    LifeAlliance: "الحياة في أليانس",
    about: "معلومات عنا",
    services: "الخدمات",
    location: "الموقع",
    abuDhabi: "أبو ظبي",
    jeddah: "جدة",
    riyadh: "الرياض",
    qatar: "قطر",
    kuwait: "الكويت",
    sharjah: "الشارقة",
    dubai: "دبي",
    oman: "عمان",
    bahrain: "البحرين",
    ManpowerRecruitment: "توظيف القوى العاملة",
    RecruitmentServices: "خدمات التوظيف",
    RecruitmentConsultant: "استشاري التوظيف",
    RecruitmentAgency: "وكالة التوظيف",
    EmploymentAgency: "وكالة التوظيف",
    ManpowerCompany: "شركة القوى العاملة",
    RPOServices: "خدمات تعهيد عمليات التوظيف",
    HRConsultant: "استشاري الموارد البشرية",
    PlacementAgency: "وكالة التوظيف",
    StaffingServices: "خدمات التوظيف",
    TempStaffingAgency: "وكالة التوظيف المؤقت",
    ITStaffingCompany: "شركة توظيف تقنية المعلومات",
    Franchise: "الامتياز التجاري",
    Executivesearch: "البحث التنفيذي",
    MedicalHealthcarestaffing: "توظيف الرعاية الصحية الطبية",
    Employmentagencyfranchise: "امتياز وكالة التوظيف",
    HRconsultancy: "استشارات الموارد البشرية",
    Recruitmentagency: "وكالة التوظيف",
    Manpowerconsultancy: "استشارات القوى العاملة",
    Staffingagencyfranchise: "امتياز وكالة التوظيف",
    HireCLevel: "توظيف كبار التنفيذيين",
    CSuite: "الإدارة التنفيذية",
    CLevel: "المستوى التنفيذي",
    learnMoreAboutCLevelRecruitment: "المستوى التنفيذي",
    cxoStaffingSolutions: "حلول توظيف المناصب التنفيذية",
    learnMoreAboutCEORecruitment: "تعرف على المزيد حول توظيف الرئيس التنفيذي",
    exploreCTORecruitmentServices: "استكشف خدمات توظيف مدير التكنولوجيا",
    cfoExecutiveSearchServices: "خدمات البحث التنفيذي للمدير المالي",
    exploreExecutiveRecruitmentDubai: "استكشف خدمات التوظيف التنفيذي في دبي",
    learnAboutCEORecruitmentServices: "تعرف على خدمات توظيف الرئيس التنفيذي",
    discoverExecutiveChefEmployment: "اكتشف فرص توظيف الطهاة التنفيذيين",
    findOutExecutiveSearchDubai: "اكتشف خدمات البحث التنفيذي في دبي",
    exploreCFOHeadhunters:
      "استكشف مديري التوظيف المالي لخدمات التوظيف الخاصة بك",
    CEO: "الرئيس التنفيذي",
    CTO: "المدير التقني",
    CXO: "المسؤول التنفيذي",
    CFO: "المدير المالي",
    ExecutiveSearch: "البحث التنفيذي",
    ExecutiveRecruitmentDubai: "توظيف التنفيذيين دبي",
    CEORecruitment: "توظيف الرؤساء التنفيذيين",
    ExecutiveChefEmployment: "توظيف الطهاة التنفيذيين",
    ExecutiveSearchDubai: "البحث التنفيذي دبي",
    Headhunter: "الباحث عن المواهب",
    HEADHUNTER: "الباحث عن المواهب",
    ExecutiveHeadhunter: "الباحث التنفيذي عن المواهب",
    CFOHeadhunters: "الباحثون عن المديرين الماليين",
    CTOHeadhunters: "الباحثون عن المديرين التقنيين",
    Industries: "الصناعات",
    WERECRUIT: "نقوم بالتوظيف في الصناعات التالية",
    healthcare: "الرعاية الصحية",
    doctor: "طبيب",
    dentist: "طبيب أسنان",
    medical: "طبي",
    nursing: "تمريض",
    executiveChef: "الطاهي التنفيذي",
    sousChef: "الطاهي المساعد",
    shipCrew: "طاقم السفينة",
    cruiseShip: "سفينة سياحية",
    driver: "سائق",
    teacher: "معلم",
    it: "تقنية المعلومات",
    legal: "القانون",
    banking: "المصرفية",
    accountant: "محاسب",
    construction: "الإنشاءات",
    engineering: "الهندسة",
    hr: "الموارد البشرية",
    marketing: "التسويق",
    hospitality: "الضيافة",
    hotel: "فندق",
    maid: "خادمة",
    photography: "التصوير",
    oilAndGas: "النفط والغاز",
    retail: "التجزئة",
    finance: "المالية",
    blog: "مدونة",
    contact: "اتصل بنا",
    postYourVacancy: "أعلن عن وظيفتك",
    franchiseInquiry: "استفسار عن الامتياز",
    hireATalent: "توظيف موهبة",
    jobSeekers: "الباحثون عن عمل",
  },
};

export const countryOptions = [
  { code: "AE", name: "UAE", href: "https://www.alliancerecruitmentagency.ae" },
  {
    code: "CA",
    name: "Canada",
    href: "https://www.alliancerecruitmentagency.ca",
  },
  {
    code: "AU",
    name: "Australia",
    href: "https://www.alliancerecruitmentagency.com.au",
  },
  {
    code: "UK",
    name: "United Kingdom",
    href: "https://www.alliancerecruitmentagency.co.uk",
  },
  {
    code: "IN",
    name: "India",
    href: "https://www.allianceinternational.co.in",
  },
  {
    code: "Global",
    name: "Global",
    href: "https://www.alliancerecruitmentagency.com",
  },
];

